### PR TITLE
Fix core install bug & remove wp-cli dependency

### PR DESCRIPTION
**Pull request by michaelsavchuk**
Ran across two hurdles when trying to install this from scratch, so this should hopefully fix them:

**First**, there doesn't seem to be a need to have wp-cli as a dependency. When I was trying to install this on a new machine, it complained the composer packages weren't installed, so I had to manually go to the packages install directory and run composer install. Removing the wp-cli dependency works just fine and the cli uses the globally isntalled wp-cli code instead (also ran across this when trying to add debug statements into the wp-cli package code and wondering why they weren't showing up).

**Second**, I would constantly be running into errors running `wp project init` and creating the database tables from the interface.
```bash
➜  ~/test  wp project init
Desired WordPress version [latest]: 
Details: Downloading WordPress latest
Success: WordPress v already installed.
Warning: wp-config.php needs to be created.
DB_NAME: wordpress
DB_USER: wordpress
DB_PASS: wordpress
DB_PREFIX [wp_]: 
DB_HOST [localhost]: 
Warning: The database needs to be created.
Created the database from details in wp-config.php and continue? [Y/n]y
Success: Database created.
Success: Starting WordPress install process...
Site Url: test.test
Site Title: test
Admin User: test
Admin Email: asdf@qwertasdfasdasd.asd
Admin Password: asdfasd
Error: The site you have requested is not installed.
Run `wp core install` to create database tables.
➜  ~/test  
```
I believe it is related to wp-cli doing a global check at the start of every command to make sure core is installed (which is weird, because it's trying to run the `wp core install` command) (see [here](https://github.com/wp-cli/wp-cli/blob/da5e38bc6240bc8d33c5d5d646d367598045176c/php/utils-wp.php#L7), used [here](https://github.com/wp-cli/wp-cli/blob/779bdd16025cb718260b35fd2b69ae47ca80cb91/php/wp-settings-cli.php#L174) and [here](https://github.com/wp-cli/wp-cli/blob/8be8a5aca7b3176a0935f5e83b7426cfc786f13f/php/WP_CLI/Runner.php#L1360). Nevertheless, changing the code from using `WP_CLI::launch` to `WP_CLI::runcommand` seems to do the trick.

### CODE REVIEW

**Comment by CurtisL** [comment]
**Regarding the first issue.**

This was an oversight on my part. `wp package install` doesn't run `install composer` so the `require_once __DIR__ . '/vendor/autoload.php';` line in `project-command.php` is the true source of this error. There is actually no need for the vendor autoloader, so that line can be removed.

Instead of removing `wp-cli` entirely, we can just move it to `require-dev` since it is useful for local dev intellisense.

**The second Issue**

I haven't been able to replicate this issue directly during the core install command. Your fix doesn't appear to cause any sort of negative side effects or issues with the commands so I don't have any objections to implementing this as a fix for now.

I am curious as to why `runcommand` worked better for you than `launch`, and how the order of the processes affect the execution of that command since a new process is created via `launch` and a child process is created via `runcommand`.

**Review by CurtisL — CHANGES_REQUESTED** [review]
Let's instead move `wp-cli/wp-cli` to `require-dev` , it is useful for local dev (intellisense).

And remove the `require_once __DIR__ . '/vendor/autoload.php'; line in project-command.php to fully address the command issue.

**Comment by michaelsavchuk** [comment]
Ended up instead doing something like https://github.com/wp-cli/package-command/blob/master/package-command.php, where they check if the autoload file exists, then load it if needed.

**Comment by CurtisL** [comment]
> Ended up instead doing something like https://github.com/wp-cli/package-command/blob/master/package-command.php, where they check if the autoload file exists, then load it if needed.

Ha ha, I had literally just looked at that repo and saw that. 👍

**Review by CurtisL — APPROVED** [review]

**Pull request merged**
